language: generic

os:
  - linux
  - osx
sudo: required
services:
  - docker

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export TARGET_NAME=darwin-x64; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export TARGET_NAME=linux-x64; fi
  - nvm install --lts
  - nvm use --lts
  - node -v
  - npm install -g esy@latest

before_script:
  - esy install
  - cd tests && npm install && cd ../

script:
  - esy build
  - cd tests && npm run test && cd ../
  - mv _build/default/src/bucklescript_bin/bin.exe graphql_ppx-$TARGET_NAME.exe

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: graphql_ppx-*.exe
  api_key:
    secure: $GH_TOKEN
  on:
    tags: true
    repo: baransu/graphql_ppx_re

jobs:
  include:
    - stage: Wait for binaries to become available
      addons:
        apt:
          sources: []
          packages: []
      before_install: skip
      before_script: skip
      deploy: []
      script:
        - bash -e ./.ci/wait_for_binaries.sh
    - stage: Deploy to npmjs
      addons:
        apt:
          sources: []
          packages: []
      before_install: skip
      before_script: skip
      script:
        - bash -e ./.ci/download_binaries.sh
      deploy:
        provider: npm
        email: tomaszcichocinski@gmail.com
        skip_cleanup: true
        api_key:
          secure: RmCpVNUsa24vHuLsEE6CSs7xe5KOLNMJLv7aOXq5+MZDpobVyD7oP9iD5LPN9+HLR+6YgWH8oG5VjMk2QrGL/U6kW1Y/gFmDbSlEZU1IHHfflCJwD11hN+iq3MDE32ATPOgtpizQvU4VX8peVcco+wufmBMW7LOMMtIaRyEJInn8eoKmPNAbG2eIedPntGmmN8nnZyoRipn2AogNUwQTXqgHGIvuEFgIAkuKY7SWvcSMLCFnCRcF2M6MLBLPSgUKHC4mO6JpRiWys2c7jtMj4pLnfL7J4E9FA/LvfjLX5b8G1apeoMpf1Qc4PeE5tjjZL7MLpsbPBTUoTcxpfCT08wOBCHcwOMyzFMYJj6TglmkFTc+6/MU/ZQjxaGjuo55cN84d38cKkW72P2iUM1pPkrBIwBOwVlhATvAPYBjDzAaVcxRfinOhntMhVtl7fuNKb3c/fK0YxwTmQIJiCoh6FwNpe96ab8mY/D0cgn1PKTd1nxXqr9gsmufAPlqEN4e0VLMlDHtejb9wlrUxAFPx+GSNxdDUIfjg4iSljotx6JBXl+1aaNhy4l9Tkuvko7PX1ir85DNc+n8ysn76LwbcpBZA1bsDGj15NrEmaBuqeMiovCaTAY/QrnmxN7IjfoyHA1FmXKeHY/U+NwBk2qow2YE3SPgld4iSCM/oBGHqcGA=
        on:
          tags: true
          repo: baransu/graphql_ppx_re
